// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NobleHabitat.Infraestructure.Data;

#nullable disable

namespace NobleHabitat.Infraestructure.Data
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Agente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OficinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OficinaId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("agentes");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.CaracteristicaInmueble", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InmuebleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId");

                    b.ToTable("caracteristicaInmuebles");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Estancia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caracteristicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InmuebleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId");

                    b.ToTable("estancias");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Inmueble", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OficinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PoseeLlaves")
                        .HasColumnType("bit");

                    b.Property<Guid>("PropietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Superficie")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ZonaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("OficinaId");

                    b.HasIndex("PropietarioId");

                    b.HasIndex("ZonaId");

                    b.ToTable("inmuebles");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Oferta", b =>
                {
                    b.Property<Guid>("InmuebleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EnAlquiler")
                        .HasColumnType("bit");

                    b.Property<bool>("EnVenta")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PrecioAlquiler")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InmuebleId");

                    b.ToTable("ofertas");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Oficina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("oficinas");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Propietario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("propietarios");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Visita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InmuebleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OficinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("InmuebleId");

                    b.HasIndex("OficinaId");

                    b.HasIndex("PropietarioId");

                    b.ToTable("visitas");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Zona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OficinaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OficinaId");

                    b.ToTable("zonas");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Agente", b =>
                {
                    b.HasOne("NobleHabitat.Domain.Entities.Oficina", "Oficina")
                        .WithMany("Agentes")
                        .HasForeignKey("OficinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NobleHabitat.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Agente")
                        .HasForeignKey("NobleHabitat.Domain.Entities.Agente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oficina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.CaracteristicaInmueble", b =>
                {
                    b.HasOne("NobleHabitat.Domain.Entities.Inmueble", "Inmueble")
                        .WithMany("Caracteristicas")
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("NobleHabitat.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("NobleHabitat.Domain.Entities.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Estancia", b =>
                {
                    b.HasOne("NobleHabitat.Domain.Entities.Inmueble", "Inmueble")
                        .WithMany("Estancias")
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Inmueble", b =>
                {
                    b.HasOne("NobleHabitat.Domain.Entities.Agente", null)
                        .WithMany("InmueblesAsignados")
                        .HasForeignKey("AgenteId");

                    b.HasOne("NobleHabitat.Domain.Entities.Oficina", "Oficina")
                        .WithMany("Inmuebles")
                        .HasForeignKey("OficinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NobleHabitat.Domain.Entities.Propietario", "Propietario")
                        .WithMany("Inmuebles")
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NobleHabitat.Domain.Entities.Zona", "Zona")
                        .WithMany("Inmuebles")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Oficina");

                    b.Navigation("Propietario");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Oferta", b =>
                {
                    b.HasOne("NobleHabitat.Domain.Entities.Inmueble", "Inmueble")
                        .WithOne("Oferta")
                        .HasForeignKey("NobleHabitat.Domain.Entities.Oferta", "InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Propietario", b =>
                {
                    b.HasOne("NobleHabitat.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Propietario")
                        .HasForeignKey("NobleHabitat.Domain.Entities.Propietario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Visita", b =>
                {
                    b.HasOne("NobleHabitat.Domain.Entities.Agente", "Agente")
                        .WithMany("Visitas")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NobleHabitat.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Visitas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NobleHabitat.Domain.Entities.Inmueble", "Inmueble")
                        .WithMany("Visitas")
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NobleHabitat.Domain.Entities.Oficina", "Oficina")
                        .WithMany()
                        .HasForeignKey("OficinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NobleHabitat.Domain.Entities.Propietario", "Propietario")
                        .WithMany()
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Cliente");

                    b.Navigation("Inmueble");

                    b.Navigation("Oficina");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Zona", b =>
                {
                    b.HasOne("NobleHabitat.Domain.Entities.Oficina", "Oficina")
                        .WithMany()
                        .HasForeignKey("OficinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oficina");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Agente", b =>
                {
                    b.Navigation("InmueblesAsignados");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Inmueble", b =>
                {
                    b.Navigation("Caracteristicas");

                    b.Navigation("Estancias");

                    b.Navigation("Oferta")
                        .IsRequired();

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Oficina", b =>
                {
                    b.Navigation("Agentes");

                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Propietario", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Agente");

                    b.Navigation("Cliente");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("NobleHabitat.Domain.Entities.Zona", b =>
                {
                    b.Navigation("Inmuebles");
                });
#pragma warning restore 612, 618
        }
    }
}
